Repository AI-Research-Center-Homepage/frontend, pull requests merged in 2022-05, with the labels that each got.

#5 feat: Create History page
  package-lock.json
  package.json
  src/App.js
  src/pages/introduction/History.js
Labels: dev

#8 feat: Add Location Page
  public/index.html
  src/App.js
  src/pages/introduction/Location.js
Labels: dev

#23 Feature/graduate page
  src/App.js
  src/components/MemberPost.js
  src/pages/member/Graduate.js
Labels: enhancement

#31 Feature/undergraduate page
  src/App.js
  src/pages/member/Undergraduate.js
Labels: dev

#28 feat: Create Researcher page
  src/App.js
  src/pages/member/Researcher.js
Labels: dev

#27 feat: Add Apply Page
  src/App.js
  src/assets/images/introImage.jpg
  src/pages/apply/Apply.js
Labels: good first issue, dev, design

#24 feat: Add Announcement Page
  src/App.js
  src/pages/News/Announcement.js
Labels: dev

#32 feat: Create Introduction page
  package-lock.json
  package.json
  src/App.js
  src/assets/intro_cclab.pdf
  src/pages/introduction/Introduction.js
  yarn.lock
Labels: dev

#36 refactor: Refactoring Header-SideMenu
  src/components/Header.js
Labels: enhancement, dev

#40 feat: Add Demo Page
  src/App.js
  src/pages/research/Demo.js
Labels: dev
